services:
  mongo:
    image: mongo
    restart: always
    logging:
      driver: none
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  backend-test:
    image: {{ env.BACKEND_IMAGE }}
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    command: npm run lint
    restart: 'no'
    depends_on:
      mongo:
        condition: service_healthy

  backend:
    image: {{ env.BACKEND_IMAGE }}
    environment:
      DB_ADDRESS: mongodb://mongo:27017/mestodb
    depends_on:
      mongo:
        condition: service_healthy
    ports:
      - 3001:3000
    healthcheck:
      interval: 10s
      timeout: 2s
      start_period: 15s
      retries: 5
      test: node healthcheck.js

  frontend-test:
    image: {{ env.FRONTEND_IMAGE }}
    command: yarn test:microfrontend
    restart: 'no'
    environment:
      CI: true

  frontend:
    image: {{ env.FRONTEND_IMAGE }}
    ports:
      - 80:3000
    depends_on:
      backend:
        condition: service_healthy
